name: CargoTest

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Main Repository
        uses: actions/checkout@v4

      - name: Configure SSH for Private Repositories
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SECRET }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Set up Rust Toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Run Cargo Tests
        run: cargo test src/ --no-fail-fast --color always